blogwebsite/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import AddPost
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='blog/logout.html'), name="logout"),
    path('add_post/', views.AddPost.as_view(), name="add_post"),
    path('full_post/<pk>', views.full_post, name='full_post'),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search, name='search'),
] 	

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogwebsite/blogwebsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
   
]

blogwebsite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.urls import reverse
import datetime

class Blogger(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to="profile_pics", default='profile_pics/default.png')
    about = models.TextField(blank=True)    



class Post(models.Model):
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE)
    title = models.TextField(max_length=400)
    post = RichTextField(blank=True, null=True)
    posted_on = models.DateTimeField(default=datetime.datetime.now())
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('full_post', args=(str(self.id)))

blogwebsite/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Blogger

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Email ID")

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Blogger
        fields = ['profile_pic']

class AboutUpadateForm(forms.ModelForm):

    class Meta:
        model = Blogger
        fields = ['about']

blogwebsite/blog/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, ProfileUpdateForm, AboutUpadateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from .models import Post, Blogger
from django.contrib.auth.models import User
from django.core.paginator import Paginator


# Create your views here.
@login_required
def home(request):
    all_post = Post.objects.filter().order_by('-posted_on')

    pagination = Paginator(all_post, 10)
    page_no = request.GET.get('page')
    page_obj = pagination.get_page(page_no)
    context = {'posts': page_obj}
    return render(request, 'blog/home.html', context)


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f'Account created for {username}! Login to continue')
            new_user = User.objects.filter(username=username).first()
            new_blogger = Blogger(user=new_user)
            new_blogger.save()
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'blog/signup.html', {'form': form})


class AddPost(CreateView):
    model = Post
    template_name = 'blog/add_post.html'
    fields = ['title', 'post']

@login_required
def full_post(request, pk):
    if request.method == "POST":
        blogger = Blogger.objects.filter(user=request.user).first()
        title = request.POST['title']
        post = request.POST['post']
        new_post = Post(blogger=blogger, title=title, post=post)
        new_post.save()
        return render(request, 'blog/full_post.html', {'post': new_post})
    else:
        post = Post.objects.filter(pk=pk).first()
        context = {'post': post}
        return render(request, 'blog/full_post.html', context)

@login_required
def profile(request):
    blogger = Blogger.objects.filter(user=request.user).first()
    if request.POST:
        print(request.POST)
        name = request.POST['updateprofile']
        print(name)
        if name == "1":
            p_form = ProfileUpdateForm(request.POST, request.FILES, instance=blogger)    
            if p_form.is_valid():
                p_form.save()
                messages.success(request, 'Profile Pic Updated')
        elif name == "2":
            u_form = AboutUpadateForm(request.POST, instance=blogger)
            if u_form.is_valid():
                u_form.save()
                messages.success(request, 'About Updated')
    
    u_form = AboutUpadateForm()
    p_form = ProfileUpdateForm()
    posts = Post.objects.filter(blogger=blogger)
    count_post = len(posts)
    context = {'posts': posts, 'blogger': blogger, 'p_form': p_form, 'u_form': u_form, 'count_post': count_post}
    return render(request, 'blog/profile.html', context)


def search(request):
    if request.method=='GET':
        query=request.GET['query']
        user1=User.objects.filter(username=query).first()
        blogger=Blogger.objects.filter(user=user1).first()
        posts = Post.objects.filter(blogger=blogger)
        count_post = len(posts)
        context = {'posts': posts, 'blogger': blogger,'count_post': count_post}
        return render(request, 'blog/search.html', context)

blogwebsite/blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div>
    <h2>Add Post</h2>
    <div class="form-group">
        <form method="POST" action="{% url 'full_post' -1 %}">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.media }}

            <button class="btn btn-outline-info">POST</button>
        </form>
    </div>

</div>

{% endblock %}

blogwebsite/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>{{ title }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/cb96d492d4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% block css_files %}

    {% endblock css_files %}
</head>

<body>

    <div class='nb'>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="#">BlogApp</a>
                <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                    &#9776;
                </button>
                <div class="collapse navbar-collapse" id="exCollapsingNavbar">
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="nav-item"><a href="{% url 'profile' %}" class="nav-link">Profile</a></li>
                    </ul>
                    <form method="get" action="/search">
                        <input type="search" name="query" placeholder="Search" autocomplete="off">
                        <button type="submit">Search</button>
                    </form>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                        <li class="dropdown order-1">
                            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">LogOut</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                        <li class="dropdown order-1">
                            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Login</a>
                        </li>
                        <li class="dropdown order-1">
                            <a href="{% url 'signup' %}" class="btn btn-outline-secondary">Sign Up</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>

    <div class="container">

    <div class="col-md-8" style="margin-top: 10%;">
        {% if messages %}
            {% for message in messages%}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %}

    {% endblock content %}
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

blogwebsite/blog/templates/blog/full_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block css_files %}

<style>
    img{
        width: 400px;
        height: 400px;
    }
</style>

{% endblock css_files %}
{% block content %}

<div>

    <blockquote class="blockquote text-center">
        <p style="font-size: xx-large; font-family: cursive;" class="mb-0">{{ post.title }}</p>
        <footer class="blockquote-footer">By <cite title="Source Title">{{ post.blogger.user.username }} on {{ post.posted_on }}</cite></footer>
    </blockquote>
    <div class="post_body" style="width: 80%; margin-left: 10%;">
        {{ post.post|safe }}
    </div>

</div>

{% endblock content %}

blogwebsite/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

<a href="{% url 'add_post' %}" style="float: right;"><button type="button" class="btn btn-dark">ADD POST</button></a><br>
<div class="posts" style="width: 70%;">
{% for post in posts %}
    <div class="card">
        <div class="card-header">
          Posted On: {{ post.posted_on }}  
        </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <a href="{% url 'full_post' post.pk %}" style="text-decoration: none;"><p>{{ post.title }}</p></a>
            <footer class="blockquote-footer">By:  <cite title="Source Title">{{ post.blogger.user.username }}</cite></footer>
          </blockquote>
        </div>
    </div>
    <br>
{% endfor %}
</div>

<div class="pagination" style="margin-bottom: 3%; margin-left: 25%;">
  <span class="step-links">
      {% if posts.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ posts.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
          Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
      </span>

      {% if posts.has_next %}
          <a href="?page={{ posts.next_page_number }}">next</a>
          <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>

{% endblock content %}

blogwebsite/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <div style="margin-bottom: 10%;">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend>LogIn Here!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'signup' %}">SignUp Here!</a>
        </small>
    </div>
    </div>
{% endblock content %}

blogwebsite/blog/templates/blog/logout.html
{% extends 'blog/base.html' %}
{% block content %}
    <div style="margin-top: 10%;">
        <h2>Logged Out Successfully</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}" style="font-size: xx-large;">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock content %}

blogwebsite/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css_files %}

<style>

body {
    background-color: whitesmoke;
    border-radius: 10px
}

.card {
    width: 80%;
    border: none;
    border-radius: 10px;
    background-color: #fff
}

.stats {
    background: #f2f5f8 !important;
    color: #000 !important
}

.articles {
    font-size: 20px;
    color: #a1aab9
}

.number1 {
    font-weight: 500
}

.followers {
    font-size: 20px;
    color: #a1aab9
}

.number2 {
    font-weight: 500
}

#id_about{
    width: 80%;
    margin-left: 10%;
}

label{
    margin-left: 40%;
    color: white;
    font-size: xx-large;
    font-family: cursive;
}

#id_profile_pic{
    margin-left: 40%;
    width: 30%;
    color: white;
}

.forms{
    border-radius: 2%;
    box-shadow: 4px 4px 4px 4xp rgba(255,255,255,0.6);
}

</style>

{% endblock css_files %}

{% block content %}

<div style="margin-top: 10%; margin-bottom: 10%;">


    <div class="container mt-5 d-flex justify-content-center">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                <div class="image"> <img src="{{ blogger.profile_pic.url }}" class="rounded" width="155"> </div>
                <div class="ml-3 w-100">
                    <h4 class="mb-0 mt-0">{{ user.username }}</h4> 
                    <p style="width: 100%; height: auto;">{{ blogger.about }}</p>
                    <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                        <div class="d-flex flex-column"> <span class="articles">Blogs</span> <span class="number1">{{ count_post }}</span> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class='buttons' style="margin-left: 40%; padding: 2%;">
        <button type='button' onclick="showupdate()" class="btn btn-dark">Update Profile</button>

    </div>

    <div class="posts" style="width: 100%; margin-top: 3%; margin-left: 10%;">
        {% for post in posts %}
            <div class="card">
                <div class="card-header">
                  Posted On: {{ post.posted_on }}
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <a href="{% url 'full_post' post.pk %}" style="text-decoration: none;"><p>{{ post.title }}</p></a>
                    <footer class="blockquote-footer">By:  <cite title="Source Title">{{ post.blogger.user.username }}</cite></footer>
                  </blockquote>
                </div>
            </div>
            <br>
        {% endfor %}
        </div>
</div>
<div class='forms' style="position: absolute; top: 10%; left:20%; background-color: rgba(0,0,0,0.6); width: 60%; visibility: hidden;" id="update_form">
    <form method="POST" enctype="multipart/form-data" id="profile_update">
        {% csrf_token %}
        {{ p_form|crispy }}
        <input type="hidden" value="1" name="updateprofile">
        <button type="submit" style="margin-left:40%;" class="btn btn-dark">Update Profile Pic</button>
    </form>

    <form method="POST" id="about_update">
        {% csrf_token %}
        {{ u_form|crispy }}
        <input type="hidden" value="2" name="updateprofile">
        <button type="submit" style="margin-left:40%;" class="btn btn-dark">Update About</button>
    </form>

    <button type="button" onclick="showupdate()" style="margin-left: 45%; margin-top: 1.3%; margin-bottom: 1%;" class="btn btn-dark">Cancel</button>
</div>

<script>

    function showupdate(){
        if (document.getElementById('update_form').style.visibility == 'hidden'){
            document.getElementById('update_form').style.visibility = 'visible';
        }
        else{
            document.getElementById('update_form').style.visibility = 'hidden';
        }
    }


</script>

{% endblock content %}

<!--

-->

blogwebsite/blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block css_files %}

<style>

body {
    background-color: whitesmoke;
    border-radius: 10px
}

.card {
    width: 80%;
    border: none;
    border-radius: 10px;
    background-color: #fff
}

.stats {
    background: #f2f5f8 !important;
    color: #000 !important
}

.articles {
    font-size: 20px;
    color: #a1aab9
}

.number1 {
    font-weight: 500
}

.followers {
    font-size: 20px;
    color: #a1aab9
}

.number2 {
    font-weight: 500
}

#id_about{
    width: 80%;
    margin-left: 10%;
}

label{
    margin-left: 40%;
    color: white;
    font-size: xx-large;
    font-family: cursive;
}

#id_profile_pic{
    margin-left: 40%;
    width: 30%;
    color: white;
}

.forms{
    border-radius: 2%;
    box-shadow: 4px 4px 4px 4xp rgba(255,255,255,0.6);
}

</style>

{% endblock css_files %}

{% block content %}

<div style="margin-top: 10%; margin-bottom: 10%;">


    <div class="container mt-5 d-flex justify-content-center">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                <div class="image"> <img src="{{ blogger.profile_pic.url }}" class="rounded" width="155"> </div>
                <div class="ml-3 w-100">
                    <h4 class="mb-0 mt-0">{{ blogger.user.username }}</h4> 
                    <p style="width: 100%; height: auto;">{{ blogger.about }}</p>
                    <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
                        <div class="d-flex flex-column"> <span class="articles">Blogs</span> <span class="number1">{{ count_post }}</span> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="posts" style="width: 100%; margin-top: 3%; margin-left: 10%;">
        {% for post in posts %}
            <div class="card">
                <div class="card-header">
                  Posted On: {{ post.posted_on }}
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <a href="{% url 'full_post' post.pk %}" style="text-decoration: none;"><p>{{ post.title }}</p></a>
                    <footer class="blockquote-footer">By:  <cite title="Source Title">{{ post.blogger.user.username }}</cite></footer>
                  </blockquote>
                </div>
            </div>
            <br>
        {% endfor %}
        </div>
</div>




{% endblock content %}

<!--

-->

blogwebsite/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

    <div style="margin-bottom: 10%;">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend>SignUp Here!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">SignUp</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Have An Account? <a class="ml-2" href="{% url 'login' %}">SignIn Here!</a>
        </small>
    </div>
    </div>
{% endblock content %}